Tidied up make file to eliminate use of dos2unix Reworked logic in imp77 to determine correct values of filename and file extension Cleaned code in pass3coff.c, pass3elf.c and pass3core.h to add new ibj record types VERSION and COMMENT

diff --git a/pass3/imp77 b/pass3/imp77
--- a/pass3/imp77
+++ b/pass3/imp77
@@ -1,11 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 # Simple IMP compiler shell wrapper
 
 CC=gcc
 
 # Compiler source and binary folders 
-TESTDIR=${IMP_SOURCE_HOME}
-RELEASEDIR=${IMP_INSTALL_HOME}
+TEST_DIR=${IMP_SOURCE_HOME}
+RELEASE_DIR=${IMP_INSTALL_HOME}
 
 PROGNAME=`basename $0`
 SHOW_LIST=false
@@ -20,6 +20,10 @@ HEAP_MODE=false
 MORETODO=true
 while ${MORETODO} ; do
    case X"$1" in
+   X-Fx)
+    TIDY_MODE=false
+	DO_LINK=false
+    ;;    
    X-c)
 	DO_LINK=false
 	;;
@@ -54,56 +58,70 @@ if [ $# -ne 1 ]; then
 fi
 
 # Determine a possible filename to compile
+FILENAME=
+SRCNAME=
+
+# See if the parameter omitted the .imp file extension
 if [ -e $1.imp ]; then
 	FILENAME=$1.imp
     SRCNAME=$1
 fi
 
+# See if the parameter omitted the .i file extension
 if [ -e $1.i ]; then
     FILENAME=$1.i
     SRCNAME=$1
 fi
 
+# See if the parameter accidentally included a file extension
 if [ -e $1 ]; then
-    FILENAME=$1
 
     # try to be ambivalent about which extension is used
-    SRCNAME=`basename $FILENAME .imp`
+    SRCNAME=`basename $1 .imp`
     SRCNAME=`basename $SRCNAME .i`
 
     # and now check that there was one (and it's been removed)
     if [ X"$SRCNAME.imp" != X"$1" ] && [ X"$SRCNAME.i" != X"$1" ]; then
-        echo "${PROGNAME}: The IMP source parameter has an invalid file extension" 1>&2
+        echo "${PROGNAME}: The source parameter $1 has an invalid file extension" 1>&2
         echo "${PROGNAME}: Legal file extensions are one of (.imp, .i)" 1>&2
 	    exit 1
+    else
+        FILENAME=$1
     fi
 
 fi
 
-
-if ${TEST_MODE}; then
-  INC_DIR=${TESTDIR}/include
-  P1_PROG=${TESTDIR}/compiler/pass1
-  P2_PROG=${TESTDIR}/compiler/pass2
-  P3_PROG=${TESTDIR}/pass3/pass3elf
-  LD_SCRIPT=${TESTDIR}/pass3/ld.i77.script
-  LIB_DIR=${TESTDIR}/lib
-else
-  INC_DIR=${RELEASEDIR}/include
-  P1_PROG=${RELEASEDIR}/bin/pass1
-  P2_PROG=${RELEASEDIR}/bin/pass2
-  P3_PROG=${RELEASEDIR}/bin/pass3elf
-  LD_SCRIPT=${RELEASEDIR}/bin/ld.i77.script
-  LIB_DIR=${RELEASEDIR}/lib
+if [[ "${FILENAME}.imp" == ".imp" ]]; then
+    echo "${PROGNAME}: The source parameter $1 has an invalid file extension" 1>&2
+    echo "${PROGNAME}: Legal file extensions are one of (.imp, .i)" 1>&2
+    exit 1
 fi
 
+if ${TEST_MODE}; then
+  INC_DIR=${TEST_DIR}/include
+  P1_PROG=${TEST_DIR}/compiler/pass1
+  P2_PROG=${TEST_DIR}/compiler/pass2
+#  P1_PROG=${TEST_DIR}/compiler/impdriver
+#  P2_PROG=
+  P3_PROG=${TEST_DIR}/pass3/pass3elf
+  LD_SCRIPT=${TEST_DIR}/pass3/ld.i77.script
+  LIB_DIR=${TEST_DIR}/lib
+else
+  INC_DIR=${RELEASE_DIR}/include
+  P1_PROG=${RELEASE_DIR}/bin/pass1
+  P2_PROG=${RELEASE_DIR}/bin/pass2
+#  P1_PROG=${RELEASE_DIR}/bin/impdriver
+#  P2_PROG=
+  P3_PROG=${RELEASE_DIR}/bin/pass3elf
+  LD_SCRIPT=${RELEASE_DIR}/bin/ld.i77.script
+  LIB_DIR=${RELEASE_DIR}/lib
+fi
 
 if ${HEAP_MODE}; then
   HEAP_OPT="-lc"
 else
   HEAP_OPT=""
 fi
-
 
 if ${SHARE_MODE}; then
   LINK_OPT="-libimp77 -lm ${HEAP_OPT} -T ${LD_SCRIPT}"
@@ -125,24 +143,26 @@ fi
 
 ${P1_PROG} ${FILENAME},${INC_DIR}/stdperm.imp=${SRCNAME}.icd,${LISTFILE}
 if [ $? -ne 0 ] ; then
-    echo "imp77: Compilation failure in pass1 for $1"
+    echo "imp77: Compilation failure in ${P1_PROG} for $1"
 	exit 1
 fi
 
 ${P2_PROG} ${SRCNAME}.icd,${FILENAME}=${SRCNAME}.ibj,${CODEFILE}
 if [ $? -ne 0 ] ; then
-    echo "imp77: Compilation failure in pass2 for $1"
+    echo "imp77: Compilation failure in ${P2_PROG} for $1"
 	exit 1
 fi
+
 if ${TIDY_MODE}; then
 	rm ${SRCNAME}.icd
 fi
 
 ${P3_PROG} ${SRCNAME}.ibj ${SRCNAME}.o
 if [ $? -ne 0 ] ; then
-    echo "imp77: Compilation failure in pass3 for $1"
+    echo "imp77: Compilation failure in ${P3_PROG} for $1"
 	exit 1
 fi
+
 if ${TIDY_MODE}; then
 	rm ${SRCNAME}.ibj
 fi
@@ -150,10 +170,12 @@ fi
 if ${DO_LINK}; then
     # Linker
     ${CC} ${M32} -no-pie -o ${SRCNAME} ${SRCNAME}.o ${LINK_OPT}
+
     if [ $? -ne 0 ] ; then
         echo "imp77: Linking failure for program $1"
         exit 1
     fi
+
 	if ${TIDY_MODE}; then
 		rm ${SRCNAME}.o
 	fi
